### PR TITLE
Fix recursive paths

### PR DESCRIPTION
**Pull request by milesburton**

### CODE REVIEW

**Comment by milesburton** [comment]
This is still very much beta code but it's better than master.

@wurmr Any comments.

**Review by wurmr — COMMENTED** [review]
Are you sure you want to delete the `.gitkeep` in the Video directory? I think this is an artifact of the running system.

Otherwise this looks good to me, I am not using dropbox but the dashcam-monitor is working well on my setup.

**Comment by wurmr** [comment]
The other change I've been running with is more headroom in the cam image files. Currently I've got them at 6gb. I might not need this any more now that the mount/umount seems stable.

**Comment by milesburton** [comment]
Fixed the missing folder.

Yeah that seems reasonable.

**Pull request merged**
